"""empty message

Revision ID: 80cc7b61a5fc
Revises: 
Create Date: 2018-10-29 21:38:37.563755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cc7b61a5fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('conditionid', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('conditionid')
    )
    op.create_table('group',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.Column('admin', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.create_index(op.f('ix_group_admin'), 'group', ['admin'], unique=True)
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=True)
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('usertype', sa.String(length=64), nullable=True),
    sa.Column('realname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('doctor',
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('doctorname', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('officename', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=32), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.PrimaryKeyConstraint('doctorid')
    )
    op.create_table('groupuser',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], )
    )
    op.create_table('message',
    sa.Column('messageid', sa.Integer(), nullable=False),
    sa.Column('messagetype', sa.String(length=32), nullable=True),
    sa.Column('messagetext', sa.String(length=256), nullable=True),
    sa.Column('messagesender', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('messageid')
    )
    op.create_table('note',
    sa.Column('noteid', sa.Integer(), nullable=False),
    sa.Column('notetype', sa.String(length=64), nullable=True),
    sa.Column('notetext', sa.String(length=1024), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('noteid')
    )
    op.create_index(op.f('ix_note_timestamp'), 'note', ['timestamp'], unique=False)
    op.create_table('visit',
    sa.Column('visitid', sa.Integer(), nullable=False),
    sa.Column('doctorname', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('nature', sa.String(length=128), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('doctorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctorid'], ['doctor.doctorid'], ),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.PrimaryKeyConstraint('visitid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_index(op.f('ix_note_timestamp'), table_name='note')
    op.drop_table('note')
    op.drop_table('message')
    op.drop_table('groupuser')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.drop_index(op.f('ix_group_admin'), table_name='group')
    op.drop_table('group')
    op.drop_table('condition')
    # ### end Alembic commands ###
