"""empty message

Revision ID: da31f48cbcdd
Revises: 
Create Date: 2018-11-05 21:17:38.280624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da31f48cbcdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('conditionid', sa.Integer(), nullable=False),
    sa.Column('conditiontext', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('conditionid')
    )
    op.create_table('group',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.Column('admin', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.create_index(op.f('ix_group_admin'), 'group', ['admin'], unique=True)
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=True)
    op.create_table('notetype',
    sa.Column('notetypeid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('notetypeid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('usertype', sa.String(length=64), nullable=True),
    sa.Column('realname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('case',
    sa.Column('caseid', sa.Integer(), nullable=False),
    sa.Column('casename', sa.String(length=128), nullable=True),
    sa.Column('casetext', sa.String(length=2048), nullable=True),
    sa.Column('startday', sa.DateTime(), nullable=True),
    sa.Column('endday', sa.DateTime(), nullable=True),
    sa.Column('endtag', sa.Boolean(), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.PrimaryKeyConstraint('caseid')
    )
    op.create_index(op.f('ix_case_casename'), 'case', ['casename'], unique=True)
    op.create_index(op.f('ix_case_endday'), 'case', ['endday'], unique=False)
    op.create_index(op.f('ix_case_startday'), 'case', ['startday'], unique=False)
    op.create_table('group_has_user',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], )
    )
    op.create_table('message',
    sa.Column('messageid', sa.Integer(), nullable=False),
    sa.Column('messagetype', sa.String(length=32), nullable=True),
    sa.Column('messagetext', sa.String(length=256), nullable=True),
    sa.Column('messagesender', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('messageid')
    )
    op.create_table('task',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tasktext', sa.String(length=128), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('taskid')
    )
    op.create_index(op.f('ix_task_timestamp'), 'task', ['timestamp'], unique=False)
    op.create_table('case_has_condition',
    sa.Column('caseid', sa.Integer(), nullable=True),
    sa.Column('conditionid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseid'], ['case.caseid'], ),
    sa.ForeignKeyConstraint(['conditionid'], ['condition.conditionid'], )
    )
    op.create_table('case_has_task',
    sa.Column('caseid', sa.Integer(), nullable=True),
    sa.Column('taskid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseid'], ['case.caseid'], ),
    sa.ForeignKeyConstraint(['taskid'], ['task.taskid'], )
    )
    op.create_table('doctor',
    sa.Column('doctorid', sa.Integer(), nullable=False),
    sa.Column('doctorname', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('officename', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=128), nullable=True),
    sa.Column('address2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=32), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('caseid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseid'], ['case.caseid'], ),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.PrimaryKeyConstraint('doctorid')
    )
    op.create_index(op.f('ix_doctor_doctorname'), 'doctor', ['doctorname'], unique=True)
    op.create_table('note',
    sa.Column('noteid', sa.Integer(), nullable=False),
    sa.Column('notetext', sa.String(length=2048), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('endtag', sa.Boolean(), nullable=True),
    sa.Column('lasteditor', sa.String(length=64), nullable=True),
    sa.Column('lastedittime', sa.DateTime(), nullable=True),
    sa.Column('caseid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('notetypeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseid'], ['case.caseid'], ),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.ForeignKeyConstraint(['notetypeid'], ['notetype.notetypeid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('noteid')
    )
    op.create_index(op.f('ix_note_timestamp'), 'note', ['timestamp'], unique=False)
    op.create_table('visit',
    sa.Column('visitid', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('visittext', sa.String(length=512), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('caseid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caseid'], ['case.caseid'], ),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.PrimaryKeyConstraint('visitid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    op.drop_index(op.f('ix_note_timestamp'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_doctor_doctorname'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_table('case_has_task')
    op.drop_table('case_has_condition')
    op.drop_index(op.f('ix_task_timestamp'), table_name='task')
    op.drop_table('task')
    op.drop_table('message')
    op.drop_table('group_has_user')
    op.drop_index(op.f('ix_case_startday'), table_name='case')
    op.drop_index(op.f('ix_case_endday'), table_name='case')
    op.drop_index(op.f('ix_case_casename'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('notetype')
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.drop_index(op.f('ix_group_admin'), table_name='group')
    op.drop_table('group')
    op.drop_table('condition')
    # ### end Alembic commands ###
